#!/usr/bin/env bash

set -e

cd "$(dirname "$0")/.."

echo "==> Installing Node dependencies…"

PACKAGE_MANAGER=$(command -v yarn >/dev/null 2>&1 && echo "yarn" || echo "npm")

$PACKAGE_MANAGER install "$@"
